import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/Components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "hexehell home",
  description: "Generated by Vercel",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {children}
        
        </body>
    </html>
  );
}
